export const paragraphGlance = 'The Republic of Felines are experiencing an extreme case of famine. The drought is the halting the citizens main source of water. The wealthy are vowing to take matters into their own hands, but no significant progress has been made. Without overlooking the lack of relief and rumors of a coup, it seems an group of bad kitties is taking advantage of the situation.'
export const paragraphAim = 'Clean water is a human right regardless of naitonality. Without it, nation’s people can’t survive. We want to help solve the crisis for the future of the nation and future nations effected by a drought.'
export const paragraphIssues = 'Given the underlying issue of the drought, the nation will have to encourage new healthcare policies and educaitnal policies, but first the Republic of Felines will need to address the issues of corruption and government style. If this isn’t addressed, then the political stability of the nation is threatened and political efficacy is withered.'

export const paragraphIS = 'With the help of supranational organizations and other state, The Republic of Felines can address the Immediate threat of thirst and negate the spread of famine.'
export const paragraphIS2 = 'Relief teams can build groundwater resources. Using technologies like handpumps and hydroponic greenhouse technology, it improves food security and reduces water use in the dry season.'

export const paragraphCloud = 'The devlopment of a new nation such as the Republic of Felines can be halted significantly by a drought. The heads of government will have to address the issues and take help from other states, or it will threaten their legitimacy as leaders. As the nations economic state is in shambles, the head of state can use the crisis as an oppurtunity to introduce new technologies and policies to help their campaign.'
export const paragraphCloud2 = 'Cloud seeding and Artificial intelligence can be used to reduce the impact of the drought as well as spark a new wave of economic growth.'
export const paragraphCloud3 = 'Cloud seading technology can facilitate participation by injecting substances such as silver iodide, potassium iodide, dry ice (solid carbon dioxide), liquid propane, or salt into clouds in order to induce precipitation.'
export const paragraphCloud4 = 'According to Atmospheric Physics Researcher from the College of Natural and Computational Science Megbar Wondie, “the lowest cost estimates published would be in the range of $27 to $53 per acre-foot (4000 m^2) to produce additional participation." and found that “during spring 2021, the effectivity of cloud-seeded technology is found 28.79%.”'